/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }
    String angka="";
    double jumlah,bil1,bil2;
    int pilih;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hasil = new javax.swing.JTextField();
        tujuh = new javax.swing.JButton();
        delapan = new javax.swing.JButton();
        enam = new javax.swing.JButton();
        lima = new javax.swing.JButton();
        empat = new javax.swing.JButton();
        sembilan = new javax.swing.JButton();
        satu = new javax.swing.JButton();
        dua = new javax.swing.JButton();
        tiga = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        c = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        koma = new javax.swing.JButton();
        nol = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        akar = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        persen = new javax.swing.JButton();

        jButton17.setText("jButton17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KALKULATOR");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        hasil.setEditable(false);
        hasil.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil);
        hasil.setBounds(50, 30, 390, 90);

        tujuh.setBackground(new java.awt.Color(0, 153, 153));
        tujuh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tujuh.setText("7");
        tujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tujuhActionPerformed(evt);
            }
        });
        jPanel1.add(tujuh);
        tujuh.setBounds(50, 220, 70, 50);

        delapan.setBackground(new java.awt.Color(0, 153, 153));
        delapan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        delapan.setText("8");
        delapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delapanActionPerformed(evt);
            }
        });
        jPanel1.add(delapan);
        delapan.setBounds(130, 220, 70, 50);

        enam.setBackground(new java.awt.Color(0, 153, 153));
        enam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enam.setText("6");
        enam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enamActionPerformed(evt);
            }
        });
        jPanel1.add(enam);
        enam.setBounds(210, 280, 70, 50);

        lima.setBackground(new java.awt.Color(0, 153, 153));
        lima.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lima.setText("5");
        lima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limaActionPerformed(evt);
            }
        });
        jPanel1.add(lima);
        lima.setBounds(130, 280, 70, 50);

        empat.setBackground(new java.awt.Color(0, 153, 153));
        empat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        empat.setText("4");
        empat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empatActionPerformed(evt);
            }
        });
        jPanel1.add(empat);
        empat.setBounds(50, 280, 70, 50);

        sembilan.setBackground(new java.awt.Color(0, 153, 153));
        sembilan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sembilan.setText("9");
        sembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sembilanActionPerformed(evt);
            }
        });
        jPanel1.add(sembilan);
        sembilan.setBounds(210, 220, 70, 50);

        satu.setBackground(new java.awt.Color(0, 153, 153));
        satu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        satu.setText("1");
        satu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuActionPerformed(evt);
            }
        });
        jPanel1.add(satu);
        satu.setBounds(50, 340, 70, 50);

        dua.setBackground(new java.awt.Color(0, 153, 153));
        dua.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dua.setText("2");
        dua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duaActionPerformed(evt);
            }
        });
        jPanel1.add(dua);
        dua.setBounds(130, 340, 70, 50);

        tiga.setBackground(new java.awt.Color(0, 153, 153));
        tiga.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tiga.setText("3");
        tiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigaActionPerformed(evt);
            }
        });
        jPanel1.add(tiga);
        tiga.setBounds(210, 340, 70, 50);

        samadengan.setBackground(new java.awt.Color(51, 51, 51));
        samadengan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        samadengan.setText("=");
        samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samadenganActionPerformed(evt);
            }
        });
        jPanel1.add(samadengan);
        samadengan.setBounds(370, 340, 70, 110);

        c.setBackground(new java.awt.Color(255, 51, 51));
        c.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel1.add(c);
        c.setBounds(50, 160, 70, 50);

        ce.setBackground(new java.awt.Color(0, 255, 51));
        ce.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ce.setText("CE");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });
        jPanel1.add(ce);
        ce.setBounds(130, 160, 70, 50);

        koma.setBackground(new java.awt.Color(0, 153, 153));
        koma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        koma.setText(".");
        koma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komaActionPerformed(evt);
            }
        });
        jPanel1.add(koma);
        koma.setBounds(210, 400, 70, 50);

        nol.setBackground(new java.awt.Color(0, 153, 153));
        nol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nol.setText("0");
        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });
        jPanel1.add(nol);
        nol.setBounds(50, 400, 150, 50);

        hapus.setBackground(new java.awt.Color(0, 153, 153));
        hapus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hapus.setText("log");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(210, 160, 70, 50);

        kali.setBackground(new java.awt.Color(153, 153, 153));
        kali.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kali.setText("×");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(290, 160, 70, 50);

        bagi.setBackground(new java.awt.Color(153, 153, 153));
        bagi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bagi.setText("÷");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(370, 160, 70, 50);

        tambah.setBackground(new java.awt.Color(153, 153, 153));
        tambah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(290, 220, 70, 50);

        kurang.setBackground(new java.awt.Color(153, 153, 153));
        kurang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(370, 220, 70, 50);

        akar.setBackground(new java.awt.Color(153, 153, 153));
        akar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        akar.setText("√");
        akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarActionPerformed(evt);
            }
        });
        jPanel1.add(akar);
        akar.setBounds(290, 280, 70, 50);

        pangkat.setBackground(new java.awt.Color(153, 153, 153));
        pangkat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pangkat.setText("x^2");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        jPanel1.add(pangkat);
        pangkat.setBounds(370, 280, 70, 50);

        persen.setBackground(new java.awt.Color(153, 153, 153));
        persen.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        persen.setText("%");
        persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenActionPerformed(evt);
            }
        });
        jPanel1.add(persen);
        persen.setBounds(290, 340, 70, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(493, 585));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enamActionPerformed
        // TODO add your handling code here:
        angka += "6";
        hasil.setText(angka);
    }//GEN-LAST:event_enamActionPerformed

    private void sembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sembilanActionPerformed
        // TODO add your handling code here:
         angka += "9";
        hasil.setText(angka);
    }//GEN-LAST:event_sembilanActionPerformed

    private void limaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limaActionPerformed
 angka += "5";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_limaActionPerformed

    private void tigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigaActionPerformed
 angka += "3";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_tigaActionPerformed

    private void samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samadenganActionPerformed
switch(pilih){
    case 1: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=bil1+bil2;
            angka=Double.toString(jumlah);
            hasil.setText(angka);
                    break;
    case 2: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=bil1-bil2;
            angka=Double.toString(jumlah);hasil.setText(angka);break;
    case 3: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=bil1*bil2;
            angka=Double.toString(jumlah);hasil.setText(angka);break;
    case 4: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=bil1/bil2;
            angka=Double.toString(jumlah);hasil.setText(angka);break;
    case 5: 
            jumlah=bil2/100;
            angka=Double.toString(jumlah);
            hasil.setText(angka);
            ;break;
    case 6: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=Math.sqrt(bil1);
            angka=Double.toString(jumlah);hasil.setText(angka);break;
    case 7: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=Math.pow(bil1,2);
            angka=Double.toString(jumlah);hasil.setText(angka);break;
    case 8: bil2=Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah=Math.log(bil1);
            angka=Double.toString(jumlah);hasil.setText(angka);break;
   }
hasil.setText(angka);// TODO add your handling code here:
        
    }//GEN-LAST:event_samadenganActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
hasil.setText("0");
angka="";

// TODO add your handling code here:
    }//GEN-LAST:event_ceActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
bil1=Double.parseDouble(angka);
hasil.setText("×");
angka="";
pilih=3;        // TODO add your handling code here:
    }//GEN-LAST:event_kaliActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
bil1=Double.parseDouble(angka);
hasil.setText("+");
angka="";
pilih=1;
// TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        bil1=Double.parseDouble(angka);
hasil.setText("÷");
angka="";
pilih=4;// TODO add your handling code here:
    }//GEN-LAST:event_bagiActionPerformed

    private void persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenActionPerformed
        // TODO add your handling code here:
        hasil.setText("%");
angka="";
pilih=5;
    }//GEN-LAST:event_persenActionPerformed

    private void satuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuActionPerformed
 angka += "1";
        hasil.setText(angka);
    }//GEN-LAST:event_satuActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
 angka += "0";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_nolActionPerformed

    private void duaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duaActionPerformed
 angka += "2";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_duaActionPerformed

    private void empatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empatActionPerformed
 angka += "4";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_empatActionPerformed

    private void tujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tujuhActionPerformed
 angka += "7";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_tujuhActionPerformed

    private void delapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delapanActionPerformed
 angka += "8";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_delapanActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
bil1=Double.parseDouble(angka);
hasil.setText("-");
angka="";
pilih=2;        // TODO add your handling code here:
    }//GEN-LAST:event_kurangActionPerformed

    private void akarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarActionPerformed
bil1=Double.parseDouble(angka);
hasil.setText("√");
angka="";
pilih=6;        // TODO add your handling code here:
    }//GEN-LAST:event_akarActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
hasil.setText(null);
bil1=0.0;
bil2=0.0;
jumlah=0.0;
angka="";// TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void komaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komaActionPerformed
angka += ".";
        hasil.setText(angka);        // TODO add your handling code here:
    }//GEN-LAST:event_komaActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
     bil1=Double.parseDouble(angka);
hasil.setText("^");
angka="";
pilih=7;      // TODO add your handling code here:
    }//GEN-LAST:event_pangkatActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
          bil1=Double.parseDouble(angka);
hasil.setText("log");
angka="";
pilih=8;    // TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
hasil.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akar;
    private javax.swing.JButton bagi;
    private javax.swing.JButton c;
    private javax.swing.JButton ce;
    private javax.swing.JButton delapan;
    private javax.swing.JButton dua;
    private javax.swing.JButton empat;
    private javax.swing.JButton enam;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton koma;
    private javax.swing.JButton kurang;
    private javax.swing.JButton lima;
    private javax.swing.JButton nol;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton persen;
    private javax.swing.JButton samadengan;
    private javax.swing.JButton satu;
    private javax.swing.JButton sembilan;
    private javax.swing.JButton tambah;
    private javax.swing.JButton tiga;
    private javax.swing.JButton tujuh;
    // End of variables declaration//GEN-END:variables
}
